import { TranslationProvider } from "@/components/UseTranslation";
import "./globals.css";

export const metadata = {
  title: "Nima Binesh",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <TranslationProvider>{children}</TranslationProvider>
      </body>
    </html>
  );
}
